export const categories = [
  {
    id: 1,
    name: 'Riddles',
    levels: [
      {
        id: 1,
        level: 1,
        points: 10,
        questionnaireId: 1,
        questionCount: 20,
        status: 'open',
      },
      {
        id: 2,
        level: 2,
        points: 0,
        questionnaireId: 2,
        questionCount: 20,
        status: 'closed',
      },
      {
        id: 3,
        level: 3,
        points: 0,
        questionnaireId: 3,
        questionCount: 20,
        status: 'closed',
      },
      {
        id: 4,
        level: 4,
        points: 0,
        questionnaireId: 4,
        questionCount: 20,
        status: 'closed',
      },
      {
        id: 5,
        level: 5,
        points: 0,
        questionnaireId: 5,
        questionCount: 20,
        status: 'closed',
      },
      {
        id: 6,
        level: 6,
        points: 0,
        questionnaireId: 6,
        questionCount: 20,
        status: 'closed',
      },
    ],
  },
  {
    id: 2,
    name: 'General Knowledge',
    levels: [
      {
        id: 1,
        level: 1,
        points: 10,
        questionCount: 20,
        status: 'open',
      },
      {
        id: 2,
        level: 2,
        points: 0,
        questionCount: 20,
        status: 'closed',
      },
      {
        id: 3,
        level: 3,
        points: 0,
        questionCount: 20,
        status: 'closed',
      },
      {
        id: 4,
        level: 4,
        points: 0,
        questionCount: 20,
        status: 'closed',
      },
      {
        id: 5,
        level: 5,
        points: 0,
        questionCount: 20,
        status: 'closed',
      },
      {
        id: 6,
        level: 6,
        points: 0,
        questionCount: 20,
        status: 'closed',
      },
    ],
  },
]
